- plugins.json
- plugins/techne_importer.js
Finished the Techne importer Wither started to write.
> Added Importer for Techne Files.

- plugins/mod_model_format_importer.js
> Fixed a bug that caused Tabula models using offset to display wrong

- plugins/optimize.js
-Increased epsilon value to combat inaccuracies
-Removed cubes can now be undone
-The invisible sides of planes now get removed
> Bug fixes to the optimize plugin

- plugins.json
- plugins/structure_importer.js
-Biome tint now gets applied
-Fixed a bug where invisible cubes could get added, making the model unable to load in minecraft
-Fixed a crash when structure voids were used
-The menu entry is now under the import button
> Bug fixes to the structure importer

- plugins.json
- plugins/mod_utils.js
Removed Techne importer temporarly.
Improved Tabula Importer.
> Updated Mod Utils plugin to work with Blockbench 3.1+

- plugins/mod_utils.js
Decreased risk of plugin incompatability.
> Added a new Help page.

- plugins/mod_utils.js
Fixed https://github.com/JannisX11/blockbench/issues/477
> Bugfix in Mod Utils Plugin

- plugins/cem_template_loader.js
Also added unsupported section for all the entities currently broken in cem
> Added 1.15 & 1.16 Entities

- plugins/cem_template_loader.js
The minecart model was actually a magma cube
> Fixed Minecart Model

- plugins/cem_template_loader.js
Illusioner was missing the hood part of the model.
> Added 'Hat' to Illusioner model.

- plugins.json
- plugins/threecore_exporter.js
**Commits in merge request**
- Pulled commits from master repo to fork repo
- Fixed a bug I found while using the plugin. (Can't test for all scenarios till you use it in normal environment and encounter it.)
- Version bumped the plugin's description, and in the `plugins.json`.
> ThreeCore Exporter: Bug fixes

- plugins/cem_template_loader.js
Added:
- Melon Golem
- Furnace Golem
- Tropical Slime
- Player
- Player [Thin]
- Elytra
- Trident
- Shield
- Arrow
Modified:
- Banner
Fixed Code Indentation
> Added new MCE Mobs, and missing Java Entities

- plugins/cem_template_loader.js
Fixed Wolf model, added new MCE Mobs
> Fixed Wolf model, added new MCE Mobs

- plugins/structure_importer.js
New Features:
-Namespaces in resource paths are now supported
-Culling is now supported for blocks up to Snapshot 20w17a
-The Action now shows in both the Filter-tab and the Import-tab
Bug fixes:
-Fixed filepaths not working in Linux
-Browsing for a directory now also works in electron version 6 and newer
-Fixed a bug where culling information sometimes got lost when the model got rotated in the blockstate file
> Updated structure importer plugin

- plugins/threecore_exporter.js
**Commits**
1. Pull changes from master to fork repos
2. - Fixed miscalculated z-coordinate for cubes inside nested groups
3. - Forgot to remove debug output lines
> Updated ThreeCore Exporter plugin

- plugins.json
- plugins/startup_tips.js
The Startup Tips plugin provides helpful tips about Blockbench on startup. 
This is a simple plugin, but one that would definitely be helpful to beginners. 
It has a good number of tips already, but feel free to add more.
> Added Startup Tips Plugin

- plugins/cem_template_loader.js
- Added new Chest models
- Added `Legacy Models` section
- Fixed Vilager model
> Full 1.15 support

- plugins.json
- plugins/animation_utils.js
I made a library to support bedrock animations in modded java edition (currently 1.15 only, will add support for older versions soon), and this plugin exports the way I need it to. Will be writing more detailed documentation on my github in the next few days.
> New plugin: Gecko's Animation Utils

- plugins.json
- plugins/multi-layer.js
Right now it just supports solid & translucent, I don't see a real reason why anyone would need to apply the other layers.
> Add multi-layer export plugin

- plugins/cem_template_loader.js
Complete Revamp of all models. Added missing unsupported entities, fixed a load of bugs.
> Complete Revamp of all models

- plugins/discord-rpc.js
This updates to a new node module which uses the new discord domain for api calls. It also adds some minor grammar corrections to deal with using 'a' or 'an' when referencing format names. The icon for skin mode has also been added.
> Update modules due to Discord API change

- plugins/cem_template_loader.js
Fixed a bug which caused villagers to not load
> Fixed a bug which caused villagers to not load

- plugins.json
- plugins/mod_utils.js
Fixes #83, #88
Also fixed UV Mirror on imported models not working
Temporarly removed the Undo functionality.
> Implement Support for Tabula model format v5

- plugins.json
- plugins/modded_entity_fabric.js
Adds support for Fabric export format for 1.14 and 1.15+
> Fabric Modded Entity exporter plugin

- plugins/cem_template_loader.js
> Updated version number

- plugins/cem_template_loader.js
> Bugfix on 1.17 entities, squid, pillager, and dolphin

- plugins.json
- plugins/datagen_export.js
Example export:
```java
this.models().withExistingParent("blockbench_export", "minecraft:block/block").ao(false).texture("particle", new ResourceLocation("whisperwoods:blocks/wisp_lantern_roof")).element().from(10.8F, 1F, 10.8F).to(11.8F, 9F, 11.8F).rotation().angle(2F).axis(Axis.Z).origin(0F, 9F, 0F).end().face(Direction.NORTH).uvs(13.5F, 7F, 14F, 11F).texture("#particle").end().face(Direction.EAST).uvs(13F, 7F, 13.5F, 11F).texture("#particle").end().face(Direction.SOUTH).uvs(14.5F, 7F, 15F, 11F).texture("#particle").end().face(Direction.WEST).uvs(14F, 7F, 14.5F, 11F).texture("#particle").end().face(Direction.UP).uvs(14F, 7F, 13.5F, 6.5F).texture("#particle").end().face(Direction.DOWN).uvs(14.5F, 6.5F, 14F, 7F).texture("#particle").end().end().element().from(3F, 8.5F, 7.5F).to(4F, 15.5F, …
```
> Add datagen export plugin

- plugins/csmodel.js
Changed Importer to import model name by importing the filename and setting the project name and geometry name and texture name.
> Changed Importer to import the model name and id.

- plugins.json
- plugins/arcaniax_block_exporter.js
Created new plugin for creating new Blocks on Bedrock Edition
> Added Bedrock Block Exporter

- plugins/animation_utils.js
- src/animation_utils/settings.js
> Fixed display tab disappearing bug

- plugins/texture_stitcher.js
A couple of bug fixes to the texture stitcher plugin.
> texture_stitcher: Max resolution when stitching and fix affecting untextured sides

- plugins/animation_utils.js
- src/animation_utils/package.json
- src/animation_utils/settings.js
Sorry Jannis, I tested it this time
> Removed max_version=3.7.99 again

- plugins/shape_generator.js
-Updated to new methods (where possible/needed)
-Fixed problem, where the max border with was calculated wrongly.
-Fixed Dialogue being closed before values could be read from it.
> 3.8 version of shape_generator

- plugins/cem_template_loader.js
Added a version number to tell you what version of the JSON file you are using, and reload button to refresh the JSON.
> Added JSON version number and reload button

- plugins.json
> remove mcearth template loader plugin

- plugins.json
- plugins/simplify.js
Simplifies the cubes in a model. For example, if a block was 0.99 pixels wide, then it would change it to 1.
> Added simplify plugin

- plugins/animation_utils.js
- src/animation_utils/animationUi.js
- src/animation_utils/index.js
Fixes GeckoLib Models being opened as generic models
> Added await_loading and fixed typo

- plugins.json
- plugins/mod_utils.js
> Mod utils mojmaps

- plugins.json
- plugins/vintagestory_models.js
Allows exporting Vintage Story models
> Vintage Story Models

- package-lock.json
- plugins.json
- plugins/brush_randomizer.js
Simple plugin to randomize your brush color within a customizable margin.
> Added brush_randomizer plugin

- plugins.json
- plugins/armor_stand_animator.js
Added pausing and resuming feature, updated model, added base plate, fixed several bugs.
> Updated ASA to 1.1.0

- plugins.json
- plugins/texture_stitcher.js
This PR makes texture stitching process work also with meshes. Thanks to wacky for reporting! 👍
> Texture Stitcher: Implement mesh UV stitching

- plugins.json
- plugins/voxel_shape_fabric_generator.js
Generate Voxel Shape files for Fabric
> Add VoxelShape Fabric Generator

- plugins/vintagestory_models.js
Fix rotations coordinate being different in each of the software.
Added texture support
> rotation bug + texture support

- plugins/arcaniax_block_exporter.js
> Removed windows specific file pathing for Arcaniax's Block Exporter

- plugins.json
- plugins/cem_template_loader.js
> Fix animation editor bug

- plugins.json
- plugins/cem_template_loader.js
> Fix switching tabs with animation editor

- plugins.json
- plugins/cem_template_loader.js
> Fix update selection bug

- plugins.json
- plugins/cem_template_loader.js
- plugins/optifine_player_models.js
The OptiFine Player Models plugin is a plugin that adds a new format to allow you to create player models to use with OptiFine.
This pull request also updates CEM Template Loader to fix some bugs.
> Add OptiFine Player Models and update CEM Template Loader

- plugins.json
- plugins/boxuv_cube_flagger.js
Updating the plugin to:
- Support markdown in description
- Update description wording to match new features of plugin
> Update BoxUV Cube Flagger to 1.1.1 to touch up description

- plugins.json
- plugins/quick_box_uv_layout.js
This plugin adds a button that rearranges the UV of selected cubes in Per-face mode into the shape of Box-UV mode.
https://user-images.githubusercontent.com/58179488/171749398-531b4f82-9fe3-407a-a5cb-adc6c6b259e5.mp4
> Add quick_box_uv_layout

- plugins.json
- plugins/cem_template_loader.js
- plugins/colour_gradient_generator.js
- plugins/optifine_player_models.js
This plugin generates hue shifted colour gradient palettes from a single colour.
This pull request also updates the formatting of CEM Template Loader and OptiFine Player Models
> Add Colour Gradient Generator plugin

- plugins.json
- plugins/animation_to_java.js
Has been tested and confirmed to be working on Forge and Fabric for 1.19.
> Add plugin to convert animation to java code

- plugins.json
- plugins/animation_to_java.js
As the title states Ive since created a fixed version  that simply sorts the keyframes before they are formatted, which seems to work fine not super efficient but it seems to work. If anyone has other ideas Im more than happy to hear them!
Before:
https://streamable.com/hpc7s9
After:
https://streamable.com/fbmp4a
> Fixed animation_to_java.js outputting keyframes out of order

- plugins.json
- plugins/cem_template_loader.js
Add new start screen
Add new animation stuff:
- Entity number variables
- Entity boolean variables
- Official print function
- Boolean print function
- Lerp function
- Entity id
- player_pos_x/y/z
- player_rot_x/y
- entity_rot_x/y
- death_time
- dimension
- frame_time
Fixed bugs:
- Error messages displaying incorrectly in animation editor
- Naming groups the same as functions causing issues
- Math.sqrt crashing if 0
- Animations crashing if a cube is selected
Removed:
- cemAnimationInvertPivotPoint
- Internal support for idle_time
- Internal support for revenge_time
> Update CEM Template Loader for 4.3.0, add new animation features, and fix bugs

- plugins.json
- plugins/root_motion_extractor.js
Adds a plugin which tries its best to estimate a velocity for an animation, and then gives you the values needed to reach that velocity for the movement component.
> Added root motion extractor plugin

- plugins.json
- plugins/root_motion_extractor.js
The plugin now also extracts the anim time factor to be used together with q.modified_distance_moved.
> Root motion extractor update: Anim time factor

- plugins.json
- plugins/mesh_flagger.js
Update Mesh Flagger to 1.0.1.
- Reword plugin description
- Re-organize `About Mesh Flagger...` dialog
- Add Discord server to `About Mesh Flagger...` dialog
- Added quick messages for installing and uninstalling the plugin
> Update Mesh Flagger to 1.0.1

- plugins.json
- plugins/boxuv_cube_flagger.js
- plugins/ground_plane_editor.js
- plugins/mesh_flagger.js
- Added quick messages for installing/uninstalling
- Added quick messages for flagging actions
- Removed unused variables
- Re-did about section in `Help > About > About BoxUV Cube Flagger...`
- Updated plugin tags
- Added quick messages for installing/uninstalling
- Added quick messages for flagging actions
- Removed unused variables
- Updated plugin tags
- Edited plugin installation quick message
- Added Discord server in `Help > About > About Ground Plane Editor...`
> Update: BoxUV Cube Flagger, Mesh Flagger, Ground Plane Editor

- plugins.json
- plugins/mod_utils.js
Fixed a bug in the old Tabula Import
Added a new Tabula Import option that utilizes a few of BBs new features. 
Relicensed Mod Utils to MIT
> Mod Utils - Bugfixes & new Feature

- plugins.json
- plugins/cem_template_loader.js
add support for the `visible` variable name
add support for the `rule_index` render variable
fix bugs with function comma checking
> Visible & rule_index support + bug fixes

- plugins.json
- plugins/cem_template_loader.js
- plugins/optifine_player_models.js
- plugins/preview_scene_customiser.js
Add credit support to the OptiFine Player Model format Keep track of model credit field in Preview Scene Customiser
Fix OptiFine Player Model format page trying to load the wrong format
> Fix optifine player model format page & add credit

- plugins.json
- plugins/image_centering.js
- Cleaned up code a bit
- Simplified some functions
- Centering can now be done with the keybind `c`
> Update Image Centering plugin to 1.1.0

- plugins.json
- plugins/backup_viewer.js
This plugin adds a backup tab to the Blockbench start screen that allows you to view a list of the project backups from within Blockbench.
> Add Backup Viewer plugin

- plugins.json
- plugins/bbs_exporter.js
This plugin adds an exporter option to export current model (in any project format) to my BBS engine.
> Add BBS exporter plugin

- plugins.json
- plugins/sam3dj.js
This plugin allows you to export a project in to the .3DJ format.
It got introduced for the CC-Peripherals mod *(java edition)*, within the SwitchCraft3 Server. *(See more [here](https://docs.sc3.io/whats-new/sc-peripherals.html#_3dj-format))*
> Add sam3DJ plugin

- plugins.json
- plugins/cem_template_loader.js
Fix styles
Fix disable rotations toggle appearing on cubes
Add new JEM format restrictions, so that people cannot break their models
> CEM Template Loader 7.0.0

- plugins.json
- plugins/bbs_exporter.js
This update adds support for exporting mesh objects
> BBS exporter: add meshes export

- plugins.json
- plugins/skin_mirror.js
- Added layer support
- Switched left and right option (so that it is consistent with the naming of the bones)
> Skin Mirror Plugin - Update 1.1.0

- plugins.json
- plugins/animation_to_java.js
A tiny correction to the `plugins.json` file, as well as a version fix.
* Version fix (1.2.0 instead of 1.2.2)
> 🐛Animation to Java Converter: Updated plugins.json & version fix.

- plugins.json
- plugins/minecraft_title_generator.js
> that moment when you find a bug immediately after the plugin was merged

- plugins.json
- plugins/minecraft_title_generator.js
hopefully the last issue i find right after release
> Fix missing pointer cursor

- plugins.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
Flat fonts were weird. This fixes that.
> Fix flat fonts in Minecraft Title Generator

- plugins/cardinal.js
> Update cardinal.js v1.0.1

- plugins.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
Added Tileables: A new type of texture that gets tiled across characters. Works across all fonts rather than being made for a specific font.
New render output dialog
Added Minecraft EULA agreement
Various bug fixes
> Minecraft Title Generator - 1.4.0 Update

- plugins.json
- plugins/cosmic_reach_model_editor/cosmic_reach_model_editor.js
Fixes the bug where a file could not be loaded due to the plugin trying to use a string as an object
> Cosmic Reach Model Editor bug fix

- plugins.json
- plugins/live_dev_reloader/changelog.json
- plugins/live_dev_reloader/live_dev_reloader.js
> [Live Dev Reloader] Fix missing `resizeWindow()` for theme reloading

- plugins.json
- plugins/emf_animation_addon/changelog.json
- plugins/emf_animation_addon/emf_animation_addon.js
Single icon changed in the doc as it was an icon used by cem template loader
> EMF plugin update 1.0.1 - minor

- plugins.json
- plugins/resource_pack_utilities/about.md
- plugins/resource_pack_utilities/changelog.json
- plugins/resource_pack_utilities/resource_pack_utilities.js
Sounds Stripper is a tool that will go through the sounds.json file in an resource pack and remove any entries that have not been modified.
JSON minification is now optional in JSON Optimiser
Updated the Lang Stripper icon
Added YouTube tutorials link
Fixed output textures failing to save
Fixed sorting of numerical file names in Animation Combiner
> [Resource Pack Utilites] Add Sounds Stripper utility & Important bug fix

- plugins.json
- plugins/emf_animation_addon/about.md
- plugins/emf_animation_addon/changelog.json
- plugins/emf_animation_addon/emf_animation_addon.js
Added functions, variables, and changes, for Entity Model Features update 2.2
> EMF addon plugin update

- plugins.json
- plugins/resource_pack_utilities/changelog.json
- plugins/resource_pack_utilities/resource_pack_utilities.js
Fixed Batch Exporter failing to parse certain bbmodel files
Fixed Batch Exporter failing to export formats where the codec ID did not match the format ID
> [Resource Pack Utilities] Batch Exporter bug fixes

- plugins.json
- plugins/cem_template_loader/cem_template_loader.js
- plugins/cem_template_loader/changelog.json
> [CEM Template Loader] "ifb()" and "frame_counter"

- plugins.json
- plugins/texture_stitcher/changelog.json
- plugins/texture_stitcher/texture_stitcher.js
I added a dialogue to be able to specify padding for stitched texture.
> Texture stitcher: add ability to specify padding between sprites

- plugins.json
- plugins/animation_to_json.js
Switch the "Animation to JsonEA Converter" plugin to "Animation to JSON Converter". The original library isn't really updated anymore, and I have [PRed](https://github.com/neoforged/NeoForge/pull/1476) its functionality into the NeoForge mod loader instead.
> Move "Animation to JsonEA Converter" to "Animation to JSON Converter"

- plugins.json
- plugins/cem_template_loader/cem_template_loader.js
- plugins/cem_template_loader/changelog.json
Added support for entity list groups
Added support for entity list headings
The root bone will no longer cause animation errors when not present in the model
> [CEM Template Loader] Update v8.4.0

- plugins.json
- plugins/tweaks_n_stuff/about.md
- plugins/tweaks_n_stuff/changelog.json
- plugins/tweaks_n_stuff/tweaks_n_stuff.js
- Removed `Image Exporter` tweak. (now part of Blockbench)
- Changed website to https://docs.lpsmods.dev/tweaks_n_stuff
> Tweaks & Stuff v1.0.2

- plugins.json
- plugins/minecraft_title_generator/changelog.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
Fixes a crash when enabling line terminators
> [Minecraft Title Generator] Fix crash

- plugins.json
- plugins/resource_pack_utilities/changelog.json
- plugins/resource_pack_utilities/resource_pack_utilities.js
Fixed Batch Exporter failing to export glTF, OBJ, FBX, and Collada models
> [Resource Pack Utilities] Fix glTF, OBJ, FBX, Collada batch export

- plugins.json
- plugins/minecraft_title_generator/changelog.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
> [Minecraft Title Generator] Fix loading presets

- plugins.json
- plugins/meshy/about.md
- plugins/meshy/changelog.json
- plugins/meshy/meshy.js
I removed the meta data feature because it caused issue with later format versions "1.19.30" and above. I also fixed the related issues of it not correctly importing without using meta data. Changed the faces to ensure that 4 points are ALWAYS included, this caused issue sometimes when importing with less than 3 points.
> Meshy 1.0.5

- plugins.json
- plugins/repeating_textures/repeating_textures.js
Now works with the Blockbench 5.0 beta. Also still working with 4.12.6.
Version bump to 3.0.0
> [Repeating Textures] Compatibility with 5.0 beta

- plugins.json
- plugins/export_to_blender/export_to_blender.js
Now works with the Blockbench 5.0 beta. Also still working with 4.12.6.
Version bump to 2.0.0
> [Export to Blender] Compatibility with 5.0 beta
