- plugins/cem_template_loader.js
Added the remaining 1.16 mobs to the unsupported section of the plugin, as well as a 1.15 chest template model with correct uv mapping.
Fixed enderman model, player models, and piglin model.
Removed the Minecraft Earth Mobs as they will be going in their own plugin to avoid clutter of this one. There are now too many so i thought it would be best to separate these two distinct things out.
> Added Strider, Zoglin, Zombified Piglin. Removed MCE Mobs

- plugins/cem_template_loader.js
Added a section for all mobs currently compatible with 1.15.2 OptiFine pre18.
Moved zombie_horse and skeleton_horse from broken/unsupported to supported
> Added OptiFine 1.15.2 pre18 support

- plugins.json
- plugins/animation_utils.js
I have been working hard on this major update to the GeckoLib Animation Utils. New features include:
- Per keyframe easing settings, implementing all curves from easings.net as well as step curve
- Ability to adjust curve shapes for elastic, bounce, and back
- Support for Forge 1.15 and Fabric 1.15 Java code templates
- Optional settings to allow user to customize package, entity type parameter, and animation file path so exported Java code is ready to build and run with no manual modifications needed
- Temporarily disabled some blockbench features for animated java entity projects that we don't yet support to minimize user confusion (hold on last frame loop type and "reverse keyframes" action)
Note that I followed your guidance that we should override/monkeypatch functions to add …
> GeckoLib Animation Utils 2.0.0

- plugins.json
- plugins/modded_entity_fabric.js
- Converting tabs to spaces broke the exporter, switching back.
- Fix bug where fabric export stuff was active in other formats.
- Add format status to fabric options UI:
> Critical fix for fabric exporter

- plugins.json
- plugins/duplicate_renamer.js
This plugin adds an action that renames all duplicate bones automatically so that exported bedrock models are able to load fine in bedrock edition and geckolib
> Initial duplicate renamer plugin commit

- plugins.json
- plugins/texture_stitcher.js
Hi, so I decided to write a simple texture stitcher plugin. The purpose of it is to be used when converting models to different formats that support single texture. For example, a person made a model using multiple textures, and wants to convert it to GeckoLib format, however, GeckoLib's code supports only one texture. 
The implementation is sufficient ~~pretty naive, I could look into a better algorithm later, but~~ (due to constraints' of project's texture width/height, the implementation is already optimal, and can't be optimized, if I understand correctly how UV mapping works in Blockbench). 😅 
Let me know if you'll have any issues with the code formatting, or the plugin. Also, thanks for the help!
P.S.: Is it me or did CI messed up something? 😕
> Add Texture Stitcher plugin

- plugins.json
- plugins/double_sided_cubes.js
Simply duplicates the selected Cube(s), flips them on all axis, inverts their scale and inflation, and fixes their position to line up with the original cube. This inversion causes a double sided rendering effect on java and I thought it would be nice to have a simple plugin that does all of these actions for you. Thanks to dragonmaster95#3249 for the solution to double sided rendering that doesn't require a plane per face of the cube.
> Added Double Sided Cubes Plugin

- plugins.json
- plugins/endimations_exporter.js
Adds a plugin for exporting Blockbench animations as JSON files in the format of _Endimator_ Animations (Endimations).
For context, _Endimator_ is a sub-library in the [Blueprint](https://github.com/team-abnormals/blueprint) Library Mod designed for complex keyframe animations on _Minecraft: Java Edition_ models. Animation JSON files used by _Endimator_ are in a unique format, and this plugin paves the way for animators making mods with _Endimator_ using Blockbench.
> Add Endimator Animations Exporter Plugin

- plugins.json
- plugins/cardinal.js
Cardinal is a quality of life plugin that changes up the Blockbench grid to have all cardinal directions as well as render them over the model. When removing, grid will automatically change back.
If you use custom CSS you can set the root variable "--cardial" (which is a color) to change the color of the cardinal notations.
(Custom CSS showcase)
> Add Cardinal [Plugin]

- plugins.json
- plugins/boxuv_cube_flagger.js
This plugin flags all cubes less than one unit on any axis. Users can flag these invalid cubes with one click (Tools > Flag Invalid Cubes) and can edit them so they are no longer invalid. This prevents the step of having to convert to Per-Face UV if they don't want to, or if it is not an option in the format.
> Adding BoxUV Cube Flagger Plugin

- plugins.json
- plugins/boxuv_cube_flagger.js
Updating BoxUV Cube Flagger to 1.1.0. Here is the changelog:
- Adding support for flagging cubes with decimal sizes, which are flagged in orange
- Use of a collapsible to organize the two buttons
- Changed around icons of buttons to become more fitting with the collapsible
> Update BoxUV Cube Flagger to support decimal sizes + reformatting

- plugins.json
- plugins/tint_preview.js
Tint Preview is a tool to help designers who work with the tint face feature of Java Block/Item models. It features the ability to quickly preview a color on tint enabled faces. Tint Preview adds two new actions to the Tools menu that allows you to toggle tinting and change the tint color.
This is my first plugin for Blockbench, any feedback is appreciated and hope it gets merged.
> Tint Preview Plugin

- plugins.json
- plugins/boxuv_cube_flagger.js
To make this plugin more user-friendly and intuitive, I added a **start screen**. This pops up when you install the plugin and can be re-opened using `Help > About Plugins... > About BoxUV Cube Flagger`.
> Update BoxUV Cube Flagger to have an introduction screen

- plugins.json
- plugins/player_statue_generator.js
Old tag was confusing people into thinking it works in all Minecraft related formats, not just in the Java Block/Item one.
> Updated tag to be less confusing.

- plugins.json
- plugins/mesh_flagger.js
Plugin functionality:
- Flag all meshes in project
- Flag six faced meshes in a project (includes cuboids but is not restricted to them)
- Comes with start screen which can be re-opened in Help > About Plugins
Plugin purpose: When working with more complicated projects that have both meshes and cubes, you may need to convert the project to a format that does not support meshes. However, you may miss some smaller meshes in your project which you may find out are missing later on. You can use this plugin to flag all the meshes in a project which will disappear before converting (or for any other purpose you may need to find them quickly.) 
Cuboid meshes can often look like regular cubes and can be confused with regular cubes, hence why you can also flag 6-faced meshes with this plugin. …
> Add Mesh Flagger plugin 1.0.0

- plugins.json
- plugins/tint_preview.js
An update to Tint Preview plugin. The latest update broke the plugin and needed to be fixed. I've also added tint presets of block colours from the game (foilage, water, grass, etc)
> Fixed Tint Preview for 4.3.0 and Added presets

- plugins.json
- plugins/root_motion_extractor.js
Fixed issue where the plugin didn't work for animations with length 0.
> Root Motion Extractor update

- plugins.json
The plugin is outdated and unfortunately I don't have the time to maintain it
> Remove Resource Pack Exporter plugin due to broken functionality

- plugins.json
- plugins/ground_plane_editor.js
This plugin allows editing the ground plane feature easily (color and opacity), making it a lot more customizable. The plugin remembers what the last input was. Use the plugin in Tools > Ground Plane Editor.
> Add Ground Plane Editor plugin

- plugins.json
- plugins/collapsible_menu_categories.js
- plugins/collapsible_start_screen_categories.js
This plugin adds a small dropdown arrow next to each category on the start menu, allowing you to collapse each category and hide their respective formats.
> Add Collapsible Start Screen Categories plugin

- plugins.json
- plugins/animation_to_java.js
Update the plugin to activate the "Animate" tab on the "Modded Entity" format to allow the plugin to be used with the format for which it is made.
> Update "Animation to Java Converter" plugin

- plugins.json
- plugins/animation_to_java.js
Before this when exporting to a Java animation txt file, not only was each file line so long it would crash eclipse but it also had some weird line breaks meaning it couldn't be formatted or directly used without manual cleanup like this.
****
Ive added a round function to each float field that not only will reduce file size considerably but also fixes formatting so it can be directly copy and pasted without issue.
> added rounding function to animation_to_java.js to fix formatting

- plugins.json
- plugins/cem_template_loader.js
The https://www.wynem.com/bot_assets/ directory will be changing to https://wynem.com/assets/
This PR switches over to the beta website format for a smooth transition to the new site.
The render images have also changed from PNG to WebP:
https://www.wynem.com/bot_assets/images/minecraft/renders/creeper.png
https://wynem.com/assets/images/minecraft/renders/creeper.webp
> Change Wynem website path due to upcoming website changes

- plugins.json
- plugins/image_centering.js
This small but useful plugin adds a button in the image mode's toolbar that centers the viewport. It's simple, easy to access, and convenient. (Quick demo attached)
https://user-images.githubusercontent.com/94301223/202323810-469b8d43-687b-4293-ae0e-616af6633091.mp4
> Add Image Centering plugin

- plugins.json
- plugins/scene_recorder.js
This plugin adds a new scene recorder that allows you to record your model and scene in a large variety of formats.
Using this plugin is very similar to using the built-in GIF Recorder.
You can find the `Record Scene...` button in the toolbar above the viewport.
- **GIF**
- Record animated GIFs in higher quality than the built-in GIF Recorder
- **MP4**
- Record an MP4 video
- **WebM**
- Record a WebM video
- **WebP**
- Record an animated WebP image
- **APNG**
- Record an animated PNG image
- **PNG Image Sequence**
- Output each frame as an individual PNG image
> Add Scene Recorder plugin

- plugins/image_centering.js
Fixes a bug where the installation quick message shows when Blockbench is opened, even if the plugin isn't being installed
> Image Centering bugfix 

- plugins.json
- plugins/highlight_generator.js
Overview:
---
This plugin supports exporting to the Highlight(Resourceful Lib) mod shape format, allowing for non axis-aligned visual bounding boxes for blocks.
The mod can be found here: https://links.resourcefulbees.com/highlight
---
I don't know what your policy is for mod support as you have a plugin for Geckolib, Highlight the mod itself (which is used to provide vanilla compat) is a bit small but the JSON API behind it which is in [Resourceful Lib](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib) is a bit bigger.
> Add Highlight mod shape generator

- plugins.json
- plugins/sam3dj.js
This pull request is a small fix for sam3DJ.
I made a small but quiet important mistake in the about/description field.
The mod is called **S**C-Peripherals, and not **C**C-Peripherals..
The description also displayed the 'state_on' part weirdly. I *(hopefully)* fixed it by displaying it like this now: `state_on`.
The underscore was invisible before.
> [Fix] Typos in sam3DJ description

- plugins.json
- plugins/skin_mirror.js
**Title**
Skin Mirror
**Desc**
Tool that allows you to mirror the arms and legs of existing skins to the other side.
**About**
This plugin adds a button under the `Tools` menu that allows you to mirror the arms and legs of existing skins to the other side. Select the type of the skin: Alek (3 Pixel Arm, customSlim) or Steve (4 Pixel Arm, custom). Next, choose whether you want to mirror from left to right, or the other way around. If everything is correct, click "Confirm".
> Added Skin Mirror Plugin 1.0.0

- plugins.json
- plugins/sam3dj.js
This PR adds a new "feature" (if you can call it that) and fixes a bug with on states that prevented exports.
The new "feature" is that if you name a cube a block texture (i.e. if the name contains `block:/`) it will use that texture on export. This also works for groups, so you no longer need to manually change textures to Minecraft ones. (It'd be nice if it actually rendered as the texture, but I don't know _nearly_ enough about JS and Blockbench's API to do that)
The on-state bug fix is simply to not recursively check on states, which _does_ unfortunately have the side effect of not allowing sub-groups to be on states; however personally I'd rather that than have the plugin not work at all.
> Some QoL changes and fixes to Sam3DJ

- plugins/explorer.js
The navigation using the breadcrumbs in the explorer does not work (at least for me), because the navigateBackTo function joins the new path without a / at the start of the path, although the input path started with a /.
The fix may be kind of dirty, but works (tested on Linux and Windows).
This PR also fixes an unclosed `<li` tag
> Explorer Plugin: fix navigateBackTo

- plugins.json
- plugins/outline_creator.js
Since my changes were minor, I don't think it's fair having my name as an author, so I am removing it
> Remove my name from outline creator plugin

- plugins.json
- plugins/bbs_exporter.js
I didn't considered Effect keyframes, so this caused an error that doesn't allows exporting a model. I also added appending `.bbs` to the file name, because BBS expects its models to be have that extension (to avoid future configuration files that are just `.json`).
> BBS model exporter: Fix keyframe exporter mishandling Effect keyframes

- plugins.json
- plugins/cube_inverter.js
- plugins/mc_text_generator.js
- plugins/outline_creator.js
A simple plugin that inverts cubes with a click of the button.
There are many cases in which inverted cubes are useful (besides outlines), but making them is not too convenient as of now. Also, UVs will get messed up, which requires manual fixing. This plugin fixes that.
To use this plugin, press the button that appears in the size fields of the cubes (located next to the inflation box). The action is also keybinded for extra convenience.
**Changelog:**
- Reword some incorrect or vague descriptions for some of the text settings
- Make layer setting only appear when the depth setting is 0
- Got rid of max limit for depth of characters
- Changed default thickness of characters
- Reworded the empty text field warning's description
- Added new characters: `$`, `/`
- Mark plugin as deprecated …
> Add Cube Inverter, update MC Text Gen and Outline Creator

- plugins.json
- plugins/voxel_shape_generator.js
This PR doesn't change any code, simply matches the plugins.json file with the plugin file data
> Fix VoxelShape generator plugin's incorrect plugin meta

- plugins/sam3dj.js
Implements option in Dialog to circumvent normal behaviour, instead assigning the cubes top face texture colour as tint and defaulting the texture to "sc-peripherals:block/white"
> Adds Texture Tint export option to sam3dj.js

- plugins.json
- plugins/figura_format.js
A Project Format designed for use with the Figura mod. It removes features not supported by Figura and renames some text fields for better clarity.
This plugin is completely isolated to the `figura` format. and should never leak out to other Project Formats.
Hopefully I did everything correctly, in terms of pull requesting this plugin into the repo
> Figura Model Format Plugin

- plugins.json
- plugins/figura_format/about.md
- plugins/figura_format/figura_format.js
- plugins/figura_format/icon.svg
Minor update changing the Project Type's name from "Figura" to "Figura Model" (community suggestion) and fully removed Particle and Sound keyframes instead of the rename patch job.
Additionally, the plugin has moved to the 4.8.0 plugin format
Currently I am assuming that "instructions no longer need to be stored in the plugin meta data" stated in the Blockbench Discord in the "4.8 API changes for plugin creators" post means that I do not need an `about` field in `plugins.json` for my plugin, as `about.md` will be used in it's stead for versions 4.8.0 and above. I am also assuming that plugins that have already updated to 4.8.0 only have the `about` field because of compatibility with 4.7.0. 
If these assumptions are incorrect at all, please let me know before merging and I'll fix it.
> Updated Figura Model Format plugin to 0.1.1

- plugins/azurelib_utils/about.md
Fixes a small issue where in azurelib_utils the text was overflowing the codeblock in the about.md
Pinging @AzureDoom to let you know about this PR
> Fix text overflowing codeblock for azurelib_utils about.md

- plugins.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
This adds a url fallback system to Minecraft Title Generator.
Previously, I moved it to jsdelivr, as that is more reliable than raw.githubusercontent, but as you know, that can be really slow to update.
Now it has an array of root URLs that it will try to load from, when it fails to load the first, it changes the root URL to the next in the array until it runs out, or sucessfully loads one.
also fix a single css issue
> Add url fallback system & font variants

- plugins.json
- plugins/sam3dj.js
Exporting within cubes that didn't had textures caused to an uncaught error because of the last feature commit for tinted values instead of texture names. This has been fixed within this patch.
The version has been dumped to 1.0.3 as well.
> sam3dj: Fixed Exporting

- plugins.json
- plugins/figura_format/about.md
- plugins/figura_format/figura_format.js
Updates the plugin to 0.1.2 making the following changes:
* Changed the style of about.md
* fixed an error related to updateProjectUV
* Removed the ability to have groups with the same name as it broke duplicating an animation
* Removed "Render Order" as Figura ignores the property
* Added an action to get the scripting path to a ModelPart
* Added an action to bake Inverse Kinematics to raw rotation keyframes
* reorganized the plugin code to hopefully be more readable in the future
Is it normal to add changes directly to a fork of this repo? 
I've been making changes in a separate repo and only updating the fork when I increment the version/make a pull request.
However, I've noticed many other prs directly committing to a fork of this repo.
Should I continue making changes in a separate …
> Update Figura Model Format to 0.1.2

- plugins.json
- plugins/double_sided_cubes.js
In the old version it created an inverted cube, but the UV was the topleft-most pixel in the texture and no texture was assigned. 
By duplicating the cube and then inverting that problem is resolved (instead of initializing a new one with the original one's data).
> Fixed bug with UVs not being inverted properly since the 4.9 update

- plugins.json
- plugins/cardinal.js
Fixed the billboarding so that the icons face the screen, rather than face the camera. This caused the icons to noticably rotate, especially when looking down from above:
Added the ability to change the icons scale from settings:
> [Cardinal] Fix billboarding, add ability to change scale

- plugins.json
- plugins/texture_stitcher.js
A little bug fix update to Texture Stitcher plugin: it fixes UV mapping when there are textures of varied resolution (16x16, 32x32 and 64x64 in the same project).
> Texture Stitcher: stitching of textures of varied resolutions

- plugins.json
- plugins/cube_inverter.js
The plugin has been broken for a while. I have plans on fixing it at some point when I update some of my plugins to the new system, but I can't do it right now, and I don't want people using it and breaking their projects in the mean time. Will un-deprecate once I look into it.
> Temporarily deprecate Cube Inverter plugin

- plugins.json
- plugins/modded_entity_fabric.js
While the `Fabric 1.14` and `Fabric 1.15-1.16` exporters added the `${header}` variable to the exported file, the `Fabric 1.17+` did not. This PR addresses this issue.
> Add ${header} to 1.17+ export in Fabric Modded Entity Plugin

- plugins.json
- plugins/sam3dj.js
The 3dj format has been upgraded to make it possible for players to sit on 3d prints, this PR implements a simple boolean and vector options to make use of those options.
I'm not entirely happy with the vector field's behavior and it's tendency to go bonkers even when the steps are defined to 0.1, but eh, it is what it is.
> Add seat options to sam3dj plugin

- plugins.json
- plugins/voxel_shape_generator.js
It was still using MCP class names, Mojang Class names are now Available for use (have been for a while), so I updated it to use the Mojang Class names, and Added Yarn.
> Update VoxelShape Generators to Actual MojMaps and added Yarn.

- plugins.json
- plugins/voxel_shape_fabric_generator.js
Improves the code generated by the **VoxelShape Fabric Generator** plugin by merging all individual shapes into a single one.
Old generated code:
```java
public VoxelShape makeShape(){
VoxelShape shape = VoxelShapes.empty();
shape = VoxelShapes.union(shape, VoxelShapes.cuboid(0.1875, 0, 0.375, 0.8125, 0.8125, 0.875));
shape = VoxelShapes.union(shape, VoxelShapes.cuboid(0.25, 0, 0.25, 0.75, 0.3125, 0.375));
shape = VoxelShapes.union(shape, VoxelShapes.cuboid(0.125, 0, 0.4375, 0.1875, 0.4375, 0.8125));
shape = VoxelShapes.union(shape, VoxelShapes.cuboid(0.8125, 0, 0.4375, 0.875, 0.4375, 0.8125));
return shape;
}
```
New generated code:
```java
public static VoxelShape makeShape() {
return VoxelShapes.union(
VoxelShapes.cuboid(0.1875, 0, 0.375, 0.8125, 0.8125, 0.875), …
```
> Improve VoxelShape Fabric Generator exporter

- plugins.json
- plugins/azurelib_utils/about.md
- plugins/azurelib_utils/changelog.json
Added support for the new changelog feature by adding a changelog based on the example here: https://github.com/JannisX11/blockbench-plugins/blob/master/plugins/minecraft_entity_wizard/changelog.json Please let me know if there an issue with it!
Adds support for the new contributes data in the plugins.json for the `azure_model` model format.
Updated the `about.md` for 1.20.6 support being stated and redid the gradle block to include the common source for multi-loader projects to match how I have it on my wiki. 
Thanks for the awesome new features in the new update!
> Adds Changelog/Website Link/Contributes data and about.md Updated

- plugins.json
- plugins/cem_template_loader/cem_template_loader.js
- plugins/cem_template_loader/changelog.json
- plugins/minecraft_title_generator/changelog.json
- plugins/minecraft_title_generator/minecraft_title_generator.js
CEM Template Loader
Minecraft Title Generator
> [CEM Template Loader & Minecraft Title Generator] Small changes and fixes

- plugins.json
- plugins/texture_stitcher/about.md
- plugins/texture_stitcher/changelog.json
- plugins/texture_stitcher/texture_stitcher.js
I didn't know if you change minimal version of Blockbench to `4.8.0` you had to change the structure of the plugin as well. This should fix plugin loading from File > Plugins > Available.
> Texture stitcher: fix downloading and update file structure

- plugins.json
- plugins/texture_stitcher/changelog.json
- plugins/texture_stitcher/texture_stitcher.js
Also, thanks for adding `has_changelog`! 👍
> Texture stitcher: fix UV coordinates broken in Java Block/Item

- plugins.json
- plugins/emf_animation_addon/changelog.json
- plugins/emf_animation_addon/emf_animation_addon.js
corrected 1.0.1 changelog
fixed settings not appearing in the plugins screen
bumped version to 1.0.2
> EMF plugin update

- plugins.json
- plugins/scene_recorder/about.md
- plugins/scene_recorder/changelog.json
- plugins/scene_recorder/scene_recorder.js
Adds new formats, and merges Scene Recorder into the GIF Recorder
> Scene Recorder 2.0

- plugins.json
- plugins/resource_pack_utilities/about.md
- plugins/resource_pack_utilities/changelog.json
- plugins/resource_pack_utilities/resource_pack_utilities.js
Chest Converter is a tool that will convert the chest textures between the 1.14 format 1.15 format.
Clock Generator is a tool that allows you to quickly and easily generate a full set of clock textures from a simple input texture.
CTM Converter is a tool that will convert compact CTM into full CTM or overlay CTM.
Image Resizer is a tool that will go through all images in a folder and resize them, relative to their original size.
Minecraft Title Converter is a tool that will convert images to be in the the Minecraft title format. This can also convert existing textures between the 1.19 and 1.20 texture formats.
Mojang Converter is a tool that will convert images to be in the the Mojang Studios logo format. This can also convert existing textures between the 1.15 and 1.16 texture formats. …
> [Resource Pack Utilities] Add new utilities

- plugins.json
- plugins/wasd_controls.js
Overall after being edited:
- New option to only enable the controls if the movement is enabled AND is holding the Right Mouse Button.
- Off by default
- Disabling the option returns to the old behavior.
- Creation of 2 new buttons: Move Faster and Move Slower, bound to shift and alt by default, with options to change it in the settings.
- The state of the 'WASD Toggle' tool is now saved across restarts.
I really like those new options, as they make the movement more in line with Blender and Godot, for example.
> [AWSD Controls] Option to only work when holding RightMouse

- plugins.json
- plugins/cem_template_loader/cem_template_loader.js
- plugins/cem_template_loader/changelog.json
Loading a template model that is missing its vanilla texture will no longer trigger the connction error state
> [CEM Template Loader] Fix missing texture triggering connection error state

- plugins.json
- plugins/animation_utils/CHANGELOG.md
- plugins/animation_utils/animation_utils.js
- plugins/animation_utils/src/codec.ts
- plugins/animation_utils/src/package-lock.json
- plugins/animation_utils/src/package.json
3.2
- 🚀 Auto-export the particle texture entry in the textures list for block/item display jsons if not defined
- 🚀 Auto-convert bedrock animation jsons to GeckoLib-supported animation jsons when exporting
- 🐞 Fix the particle texture entry not exporting if the name doesn't end in .png
- 🐞 Fixed item_display_transforms being shipped with .geo jsons for non-bedrock models
- 🐞 Forced known forward-compatible versions to export as 1.12.0 to maintain compatibility while we work out a better system
> Animation Utils 3.2

- plugins.json
- plugins/animation_utils/CHANGELOG.md
- plugins/animation_utils/animation_utils.js
- plugins/animation_utils/src/codec.ts
- plugins/animation_utils/src/package-lock.json
- plugins/animation_utils/src/package.json
- 🐞 Fix some animation exporting issues with specific animation setup cases
Apparently none of my test cases had this specific edge-case in there to catch this -.-
Sorry!
> Animation Utils 3.2.1

- plugins.json
- plugins/bbs_exporter/bbs_exporter.js
- plugins/bbs_exporter/changelog.json
My users have noticed that models were exported with the plugin with incorrect texture width and height. The problem was inconsistency with File > Project > Texture size and texture's actual size.
> BBS exporter: Use applied texture's size for UVs

- plugins.json
- plugins/outliner_group_exporter/changelog.json
- plugins/outliner_group_exporter/outliner_group_exporter.js
I forgot to publish my "Group Exporter" plugin into the `plugins.json` file. Should now be ready to go
> Fix "Group Exporter" not available in Blockbench

- README.md
This pull request makes a minor correction to the documentation by fixing a typo in the requirements list for submitting plugins. No functional or code changes are included.
* Fixed a typo in the `README.md` requirements section, changing "to some extend" to "to some extent"
> Fix typo in README regarding plugin curation
